#![allow(clippy::unwrap_used, clippy::expect_used)]
//! Story 4.1 — WebAuthn registration ceremony, end to end at the HTTP layer.
//!
//! These drive the *real* two-round ceremony against a `SoftPasskey` software
//! authenticator (`webauthn-authenticator-rs`), not a stub: the challenge is
//! generated by the kernel's real relying party, signed by a real COSE key, and
//! verified by `webauthn-rs`. A stubbed credential would prove only that our
//! plumbing round-trips JSON; this proves the ceremony actually verifies.
//!
//! Requires Postgres + Redis (the standard integration-test environment).

mod common;

use axum::body::Body;
use axum::http::{Request, StatusCode};
use common::TestApp;
use webauthn_authenticator_rs::WebauthnAuthenticator;
use webauthn_authenticator_rs::softpasskey::SoftPasskey;

/// A fixture username nothing else in this database has ever used.
///
/// The shared test database is not reset between runs, and
/// `create_test_user` upserts on `LOWER(name)`, so a fixed username resolves to
/// the *same* user row on every run, carrying that row's credentials and audit
/// events forward with it. The per-user assertions below are exact counts, so
/// the second run against a database sees the first run's rows and fails. A
/// fresh name per run gives each test a user whose history is only its own.
///
/// Derive the email from the name too. `users.mail` is unique on `LOWER(mail)`
/// and the upsert only resolves the *name* conflict, so a fresh name paired with
/// a fixed address trades the stale-count failure for a unique violation.
fn unique_username(prefix: &str) -> String {
    format!(
        "{prefix}_{}",
        &uuid::Uuid::now_v7().simple().to_string()[..12]
    )
}

/// Extract the CSRF token from the passkeys page (rendered into base.html's
/// `<meta name="csrf-token">`).
async fn csrf_token(app: &TestApp, cookies: &str) -> String {
    let response = app
        .request_with_cookies(
            Request::get("/user/passkeys").body(Body::empty()).unwrap(),
            cookies,
        )
        .await;
    assert_eq!(
        response.status(),
        StatusCode::OK,
        "the passkeys page should render for a logged-in user"
    );
    let body = axum::body::to_bytes(response.into_body(), 2_000_000)
        .await
        .unwrap();
    let html = String::from_utf8_lossy(&body);
    let pos = html
        .find("csrf-token")
        .expect("passkeys page must expose a csrf-token meta tag");
    let start = html[pos..]
        .find("content=\"")
        .map(|p| pos + p + 9)
        .expect("csrf-token meta tag must have content");
    let end = html[start..].find('"').map(|p| start + p).unwrap();
    html[start..end].to_string()
}

/// The origin the kernel's relying party accepts, so the soft authenticator
/// signs against the same origin the server will check.
fn rp_origin(app: &TestApp) -> url::Url {
    app.state
        .webauthn()
        .get_allowed_origins()
        .first()
        .expect("the relying party must have an origin")
        .clone()
}

async fn json_body(response: axum::response::Response) -> serde_json::Value {
    let bytes = axum::body::to_bytes(response.into_body(), 2_000_000)
        .await
        .unwrap();
    serde_json::from_slice(&bytes).unwrap_or(serde_json::Value::Null)
}

/// Drive `/register/start`, sign with the soft authenticator, and POST
/// `/register/finish`. Returns the finish response so a caller can assert on it.
async fn register_passkey(
    app: &TestApp,
    cookies: &str,
    csrf: &str,
    authenticator: &mut WebauthnAuthenticator<SoftPasskey>,
    device_name: Option<&str>,
) -> axum::response::Response {
    let start = app
        .request_with_cookies(
            Request::post("/user/webauthn/register/start")
                .header("x-csrf-token", csrf)
                .body(Body::empty())
                .unwrap(),
            cookies,
        )
        .await;
    assert_eq!(
        start.status(),
        StatusCode::OK,
        "register/start should succeed"
    );

    // CSRF tokens are single-use, so /start hands back the token /finish needs.
    let started = json_body(start).await;
    let finish_csrf = started["csrf_token"]
        .as_str()
        .expect("start must hand back a fresh CSRF token for finish")
        .to_string();
    let challenge: webauthn_rs::prelude::CreationChallengeResponse =
        serde_json::from_value(started["options"].clone()).expect("valid creation challenge");

    let credential = authenticator
        .do_registration(rp_origin(app), challenge)
        .expect("the soft authenticator should complete the ceremony");

    app.request_with_cookies(
        Request::post("/user/webauthn/register/finish")
            .header("content-type", "application/json")
            .header("x-csrf-token", &finish_csrf)
            .body(Body::from(
                serde_json::json!({
                    "credential": credential,
                    "device_name": device_name,
                })
                .to_string(),
            ))
            .unwrap(),
        cookies,
    )
    .await
}

#[test]
fn registers_a_passkey_end_to_end() {
    common::run_test(async {
        let app = common::shared_app().await;
        let username = unique_username("wa_reg_ok");
        let cookies = app
            .create_and_login_user(
                &username,
                "test-password-123",
                &format!("{username}@example.com"),
            )
            .await;
        let csrf = csrf_token(app, &cookies).await;

        let mut authenticator = WebauthnAuthenticator::new(SoftPasskey::new(true));
        let finish = register_passkey(
            app,
            &cookies,
            &csrf,
            &mut authenticator,
            Some("Work laptop"),
        )
        .await;

        assert_eq!(
            finish.status(),
            StatusCode::OK,
            "register/finish should succeed"
        );
        let body = json_body(finish).await;
        assert_eq!(body["success"], true);
        assert_eq!(body["device_name"], "Work laptop");

        // AC-2: the credential is persisted with its denormalized columns.
        let user_id: uuid::Uuid = sqlx::query_scalar("SELECT id FROM users WHERE name = $1")
            .bind(&username)
            .fetch_one(&app.db)
            .await
            .unwrap();

        let row: (String, i64, Option<String>) = sqlx::query_as(
            "SELECT credential_id, sign_count, device_name FROM webauthn_credentials WHERE user_id = $1",
        )
        .bind(user_id)
        .fetch_one(&app.db)
        .await
        .expect("the registered credential should be stored");

        assert!(!row.0.is_empty(), "credential_id must be recorded");
        assert_eq!(row.2.as_deref(), Some("Work laptop"));

        // The authoritative blob must deserialize back into a usable Passkey.
        let blob: serde_json::Value =
            sqlx::query_scalar("SELECT passkey_json FROM webauthn_credentials WHERE user_id = $1")
                .bind(user_id)
                .fetch_one(&app.db)
                .await
                .unwrap();
        let _passkey: webauthn_rs::prelude::Passkey =
            serde_json::from_value(blob).expect("stored blob must be a valid Passkey");

        // AC-5: the registration emitted a structured audit event.
        let audited: i64 = sqlx::query_scalar(
            "SELECT COUNT(*) FROM security_audit_log WHERE user_id = $1 AND kind = 'passkey.registered' AND outcome = 'success'",
        )
        .bind(user_id)
        .fetch_one(&app.db)
        .await
        .unwrap();
        assert_eq!(
            audited, 1,
            "registration must append exactly one audit event"
        );

        // And it must never have stored the raw credential id as the subject.
        let subject: Option<String> = sqlx::query_scalar(
            "SELECT subject_hash FROM security_audit_log WHERE user_id = $1 AND kind = 'passkey.registered'",
        )
        .bind(user_id)
        .fetch_one(&app.db)
        .await
        .unwrap();
        let subject = subject.expect("the audit event must carry a hashed subject");
        assert_eq!(subject.len(), 64, "subject must be a SHA-256 hex digest");
        assert_ne!(subject, row.0, "the raw credential id must never be stored");
    });
}

#[test]
fn register_start_requires_an_authenticated_session() {
    common::run_test(async {
        let app = common::shared_app().await;
        let response = app
            .request(
                Request::post("/user/webauthn/register/start")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await;
        // `require_login` redirects rather than 401s; the point is that an
        // anonymous caller never reaches the ceremony.
        assert_eq!(
            response.status(),
            StatusCode::SEE_OTHER,
            "an anonymous caller must not be able to start a registration"
        );
    });
}

#[test]
fn register_start_requires_csrf() {
    common::run_test(async {
        let app = common::shared_app().await;
        let username = unique_username("wa_reg_csrf");
        let cookies = app
            .create_and_login_user(
                &username,
                "test-password-123",
                &format!("{username}@example.com"),
            )
            .await;

        let response = app
            .request_with_cookies(
                Request::post("/user/webauthn/register/start")
                    .body(Body::empty())
                    .unwrap(),
                &cookies,
            )
            .await;
        assert_eq!(
            response.status(),
            StatusCode::FORBIDDEN,
            "a state-changing ceremony start must require the CSRF header"
        );
    });
}

#[test]
fn register_finish_without_a_ceremony_is_rejected_and_audited() {
    common::run_test(async {
        let app = common::shared_app().await;
        let username = unique_username("wa_reg_noceremony");
        let cookies = app
            .create_and_login_user(
                &username,
                "test-password-123",
                &format!("{username}@example.com"),
            )
            .await;
        let csrf = csrf_token(app, &cookies).await;

        // A syntactically valid but unsolicited credential: there is no
        // ceremony in the session, so this must be refused before verification.
        let mut authenticator = WebauthnAuthenticator::new(SoftPasskey::new(true));
        let webauthn = app.state.webauthn();
        let (challenge, _discarded_state) = webauthn
            .start_passkey_registration(uuid::Uuid::now_v7(), "someone", "Someone", None)
            .unwrap();
        let credential = authenticator
            .do_registration(rp_origin(app), challenge)
            .unwrap();

        let response = app
            .request_with_cookies(
                Request::post("/user/webauthn/register/finish")
                    .header("content-type", "application/json")
                    .header("x-csrf-token", &csrf)
                    .body(Body::from(
                        serde_json::json!({ "credential": credential }).to_string(),
                    ))
                    .unwrap(),
                &cookies,
            )
            .await;

        assert_eq!(
            response.status(),
            StatusCode::BAD_REQUEST,
            "a finish with no in-flight ceremony must be rejected"
        );

        let user_id: uuid::Uuid = sqlx::query_scalar("SELECT id FROM users WHERE name = $1")
            .bind(&username)
            .fetch_one(&app.db)
            .await
            .unwrap();
        // The user is new to this run, so the rejection this test provoked is
        // the only `registration_failed` event it can possibly have.
        let reason: Option<String> = sqlx::query_scalar(
            "SELECT details->>'reason' FROM security_audit_log
             WHERE user_id = $1 AND kind = 'passkey.registration_failed'",
        )
        .bind(user_id)
        .fetch_optional(&app.db)
        .await
        .unwrap()
        .flatten();
        assert_eq!(
            reason.as_deref(),
            Some("no_ceremony_in_progress"),
            "the specific rejection reason must be audited, not just 'it failed'"
        );
    });
}

#[test]
fn a_ceremony_is_single_use() {
    common::run_test(async {
        let app = common::shared_app().await;
        let username = unique_username("wa_reg_replay");
        let cookies = app
            .create_and_login_user(
                &username,
                "test-password-123",
                &format!("{username}@example.com"),
            )
            .await;
        let csrf = csrf_token(app, &cookies).await;

        // Start once, then finish twice with the same signed credential.
        let start = app
            .request_with_cookies(
                Request::post("/user/webauthn/register/start")
                    .header("x-csrf-token", &csrf)
                    .body(Body::empty())
                    .unwrap(),
                &cookies,
            )
            .await;
        let started = json_body(start).await;
        let finish_csrf = started["csrf_token"].as_str().unwrap().to_string();
        let challenge: webauthn_rs::prelude::CreationChallengeResponse =
            serde_json::from_value(started["options"].clone()).unwrap();

        let mut authenticator = WebauthnAuthenticator::new(SoftPasskey::new(true));
        let credential = authenticator
            .do_registration(rp_origin(app), challenge)
            .unwrap();
        let payload = serde_json::json!({ "credential": credential }).to_string();

        let first = app
            .request_with_cookies(
                Request::post("/user/webauthn/register/finish")
                    .header("content-type", "application/json")
                    .header("x-csrf-token", &finish_csrf)
                    .body(Body::from(payload.clone()))
                    .unwrap(),
                &cookies,
            )
            .await;
        assert_eq!(first.status(), StatusCode::OK);

        // A fresh token, so the replay is rejected by the ceremony state check,
        // not incidentally by CSRF.
        let replay_csrf = csrf_token(app, &cookies).await;
        let replay = app
            .request_with_cookies(
                Request::post("/user/webauthn/register/finish")
                    .header("content-type", "application/json")
                    .header("x-csrf-token", &replay_csrf)
                    .body(Body::from(payload))
                    .unwrap(),
                &cookies,
            )
            .await;
        assert_eq!(
            replay.status(),
            StatusCode::BAD_REQUEST,
            "the ceremony state is consumed at finish; a replay has nothing to verify against"
        );
    });
}

#[test]
fn a_user_can_register_several_passkeys() {
    common::run_test(async {
        let app = common::shared_app().await;
        let username = unique_username("wa_reg_multi");
        let cookies = app
            .create_and_login_user(
                &username,
                "test-password-123",
                &format!("{username}@example.com"),
            )
            .await;
        let csrf = csrf_token(app, &cookies).await;

        // Two distinct authenticators — the design's "0..N passkeys" account shape.
        let mut phone = WebauthnAuthenticator::new(SoftPasskey::new(true));
        let mut laptop = WebauthnAuthenticator::new(SoftPasskey::new(true));

        assert_eq!(
            register_passkey(app, &cookies, &csrf, &mut phone, Some("Phone"))
                .await
                .status(),
            StatusCode::OK
        );
        let csrf2 = csrf_token(app, &cookies).await;
        assert_eq!(
            register_passkey(app, &cookies, &csrf2, &mut laptop, Some("Laptop"))
                .await
                .status(),
            StatusCode::OK
        );

        let user_id: uuid::Uuid = sqlx::query_scalar("SELECT id FROM users WHERE name = $1")
            .bind(&username)
            .fetch_one(&app.db)
            .await
            .unwrap();
        let count: i64 =
            sqlx::query_scalar("SELECT COUNT(*) FROM webauthn_credentials WHERE user_id = $1")
                .bind(user_id)
                .fetch_one(&app.db)
                .await
                .unwrap();
        assert_eq!(count, 2, "an account holds multiple passkeys in parallel");
    });
}

#[test]
fn registering_a_passkey_leaves_the_password_untouched() {
    common::run_test(async {
        // D-33: credentials are PARALLEL to the password. Adding a passkey must
        // not remove, weaken, or bypass password login.
        let app = common::shared_app().await;
        let username = unique_username("wa_reg_parallel");
        let password = "test-password-123";
        let cookies = app
            .create_and_login_user(&username, password, &format!("{username}@example.com"))
            .await;
        let csrf = csrf_token(app, &cookies).await;

        let mut authenticator = WebauthnAuthenticator::new(SoftPasskey::new(true));
        assert_eq!(
            register_passkey(app, &cookies, &csrf, &mut authenticator, None)
                .await
                .status(),
            StatusCode::OK
        );

        // The password hash is still set...
        let pass: Option<String> = sqlx::query_scalar("SELECT pass FROM users WHERE name = $1")
            .bind(&username)
            .fetch_one(&app.db)
            .await
            .unwrap();
        assert!(
            pass.is_some_and(|p| !p.is_empty()),
            "registering a passkey must not clear the password"
        );

        // ...and still works.
        let _ = app.login(&username, password).await;
    });
}
