[package]
name = "trovato_image_styles"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Image styles plugin for Trovato"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
trovato-sdk = { path = "../../crates/plugin-sdk" }
serde = { workspace = true }
serde_json = { workspace = true }
