-- Add structured change summary to revisions (Story 45.1).
-- Auto-generated by the kernel when a revision is created, diffing
-- the previous revision's JSONB fields against the new one.
-- NULL for the first revision of a new item (no previous to diff).

ALTER TABLE item_revision ADD COLUMN change_summary JSONB;
