//! Vector store service for semantic search via embeddings.
//!
//! Provides the [`VectorStore`] trait for pluggable embedding storage
//! and a [`PgVectorStore`] implementation using the pgvector extension.
//! When pgvector is not installed, embedding features are gracefully
//! disabled with a startup warning.

use std::sync::Arc;

use anyhow::{Context, Result};
use sqlx::PgPool;
use tracing::{info, warn};
use uuid::Uuid;

// ============================================================================
// Types
// ============================================================================

/// A stored embedding with its metadata.
#[derive(Debug, Clone)]
pub struct StoredEmbedding {
    /// Database row ID.
    pub id: Uuid,
    /// The item this embedding belongs to.
    pub item_id: Uuid,
    /// Which field the embedding was generated from.
    pub field_name: String,
    /// The embedding model used (e.g., "text-embedding-3-small").
    pub model: String,
    /// Vector dimensions.
    pub dimensions: i32,
    /// Unix timestamp when the embedding was created.
    pub created_at: i64,
}

/// A similarity search result with distance score.
#[derive(Debug, Clone)]
pub struct SimilarityResult {
    /// The item ID.
    pub item_id: Uuid,
    /// Cosine similarity score (0.0 = identical, 2.0 = opposite).
    pub distance: f64,
    /// The field this embedding was generated from.
    pub field_name: String,
}

// ============================================================================
// Trait
// ============================================================================

/// Pluggable vector storage backend for embedding-based search.
///
/// The default implementation uses pgvector. Plugins can register
/// alternative backends (e.g., Qdrant, Pinecone) via `tap_vector_store`.
#[allow(async_fn_in_trait)] // Only used with concrete types, not dyn dispatch.
pub trait VectorStore: Send + Sync {
    /// Store an embedding for an item field.
    ///
    /// Upserts: if an embedding already exists for the same
    /// `(item_id, field_name, model)` triple, it is replaced.
    async fn store_embedding(
        &self,
        item_id: Uuid,
        field_name: &str,
        model: &str,
        embedding: &[f32],
    ) -> Result<()>;

    /// Find items similar to the given embedding vector.
    ///
    /// Returns up to `limit` results ordered by cosine similarity,
    /// filtered to embeddings generated by the current `model`.
    async fn similarity_search(
        &self,
        embedding: &[f32],
        model: &str,
        limit: u32,
    ) -> Result<Vec<SimilarityResult>>;

    /// Delete all embeddings for an item.
    async fn delete_embeddings(&self, item_id: Uuid) -> Result<u64>;

    /// Mark all embeddings with a specific model as stale.
    ///
    /// Called when the admin changes the embedding model. Stale
    /// embeddings are excluded from search and queued for re-generation.
    async fn mark_stale(&self, model: &str) -> Result<u64>;

    /// Check if the vector store backend is available.
    async fn is_available(&self) -> bool;
}

// ============================================================================
// pgvector implementation
// ============================================================================

/// PostgreSQL pgvector-based vector store.
///
/// Uses the `item_embeddings` table created by the migration. If pgvector
/// is not installed, all operations return graceful errors and
/// [`Self::is_available`] returns `false`.
pub struct PgVectorStore {
    pool: PgPool,
    available: bool,
}

impl PgVectorStore {
    /// Create a new pgvector store, checking if the extension is available.
    pub async fn new(pool: PgPool) -> Self {
        let available = Self::check_pgvector(&pool).await;
        if available {
            info!("pgvector extension available — embedding features enabled");
        } else {
            warn!("pgvector extension not available — embedding features disabled");
        }
        Self { pool, available }
    }

    /// Check if pgvector is installed by querying for the vector type.
    async fn check_pgvector(pool: &PgPool) -> bool {
        sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS(SELECT 1 FROM pg_type WHERE typname = 'vector')",
        )
        .fetch_one(pool)
        .await
        .unwrap_or(false)
    }
}

impl VectorStore for PgVectorStore {
    async fn store_embedding(
        &self,
        item_id: Uuid,
        field_name: &str,
        model: &str,
        embedding: &[f32],
    ) -> Result<()> {
        if !self.available {
            anyhow::bail!("pgvector not available");
        }

        let dimensions = embedding.len() as i32;
        // Format embedding as pgvector literal: [1.0, 2.0, 3.0]
        let vector_str = format!(
            "[{}]",
            embedding
                .iter()
                .map(|f| f.to_string())
                .collect::<Vec<_>>()
                .join(",")
        );

        sqlx::query(
            r#"
            INSERT INTO item_embeddings (item_id, field_name, model, dimensions, embedding)
            VALUES ($1, $2, $3, $4, $5::vector)
            ON CONFLICT (item_id, field_name, model)
            DO UPDATE SET
                dimensions = EXCLUDED.dimensions,
                embedding = EXCLUDED.embedding,
                created_at = EXTRACT(EPOCH FROM now())::BIGINT
            "#,
        )
        .bind(item_id)
        .bind(field_name)
        .bind(model)
        .bind(dimensions)
        .bind(&vector_str)
        .execute(&self.pool)
        .await
        .context("failed to store embedding")?;

        Ok(())
    }

    async fn similarity_search(
        &self,
        embedding: &[f32],
        model: &str,
        limit: u32,
    ) -> Result<Vec<SimilarityResult>> {
        if !self.available {
            return Ok(Vec::new());
        }

        let vector_str = format!(
            "[{}]",
            embedding
                .iter()
                .map(|f| f.to_string())
                .collect::<Vec<_>>()
                .join(",")
        );

        let rows = sqlx::query_as::<_, (Uuid, f64, String)>(
            r#"
            SELECT item_id, (embedding <=> $1::vector) AS distance, field_name
            FROM item_embeddings
            WHERE model = $2
            ORDER BY embedding <=> $1::vector
            LIMIT $3
            "#,
        )
        .bind(&vector_str)
        .bind(model)
        .bind(limit as i64)
        .fetch_all(&self.pool)
        .await
        .context("similarity search failed")?;

        Ok(rows
            .into_iter()
            .map(|(item_id, distance, field_name)| SimilarityResult {
                item_id,
                distance,
                field_name,
            })
            .collect())
    }

    async fn delete_embeddings(&self, item_id: Uuid) -> Result<u64> {
        if !self.available {
            return Ok(0);
        }

        let result = sqlx::query("DELETE FROM item_embeddings WHERE item_id = $1")
            .bind(item_id)
            .execute(&self.pool)
            .await
            .context("failed to delete embeddings")?;

        Ok(result.rows_affected())
    }

    async fn mark_stale(&self, model: &str) -> Result<u64> {
        if !self.available {
            return Ok(0);
        }

        // Mark as stale by deleting embeddings for the old model.
        // Re-embedding will be handled by a cron task or on-demand.
        let result = sqlx::query("DELETE FROM item_embeddings WHERE model = $1")
            .bind(model)
            .execute(&self.pool)
            .await
            .context("failed to mark embeddings stale")?;

        Ok(result.rows_affected())
    }

    async fn is_available(&self) -> bool {
        self.available
    }
}

/// Create the default vector store (pgvector).
pub async fn create_default_vector_store(pool: PgPool) -> Arc<PgVectorStore> {
    Arc::new(PgVectorStore::new(pool).await)
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    /// A mock vector store for testing that stores nothing.
    struct MockVectorStore;

    impl VectorStore for MockVectorStore {
        async fn store_embedding(
            &self,
            _item_id: Uuid,
            _field_name: &str,
            _model: &str,
            _embedding: &[f32],
        ) -> Result<()> {
            Ok(())
        }

        async fn similarity_search(
            &self,
            _embedding: &[f32],
            _model: &str,
            _limit: u32,
        ) -> Result<Vec<SimilarityResult>> {
            Ok(vec![SimilarityResult {
                item_id: Uuid::nil(),
                distance: 0.5,
                field_name: "body".to_string(),
            }])
        }

        async fn delete_embeddings(&self, _item_id: Uuid) -> Result<u64> {
            Ok(0)
        }

        async fn mark_stale(&self, _model: &str) -> Result<u64> {
            Ok(0)
        }

        async fn is_available(&self) -> bool {
            true
        }
    }

    #[tokio::test]
    async fn mock_vector_store_works() {
        let store = MockVectorStore;
        assert!(store.is_available().await);

        let results = store
            .similarity_search(&[1.0, 2.0, 3.0], "test-model", 10)
            .await
            .unwrap();
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].distance, 0.5);
    }

    #[tokio::test]
    async fn mock_store_delete_returns_zero() {
        let store = MockVectorStore;
        let count = store.delete_embeddings(Uuid::nil()).await.unwrap();
        assert_eq!(count, 0);
    }
}
