//! The kernel→daemon direction: an admin edit becomes an `UPDATE ng_devices`.
//!
//! `tap_item_update` fires on an admin's edit of an `ng_device` Item and hands
//! the plugin the saved Item as JSON. This module turns that JSON into exactly
//! one statement, and the interesting part is what the statement **cannot** say.
//!
//! # The two guarantees, and where each one lives
//!
//! **Column discipline** — "daemon columns never clobbered by the plugin". The
//! `SET` list is generated by iterating [`crate::columns::USER_OWNED`], not by
//! reading the payload. A field the plugin does not recognise cannot become a
//! column, and a daemon column cannot appear even if the Item somehow carried a
//! field named after one. [`build_update`] returns the column list alongside the
//! SQL so a test can assert on it directly rather than by grepping a string.
//!
//! **Loop termination** — `sync_state` is in the daemon's set
//! ([`crate::columns::DAEMON_OWNED`]), so it is not iterated and the statement
//! cannot raise it. A row the write-back touches stays `clean`, so the next
//! cron pass does not select it. Under the frozen contract the loop cannot even
//! start (`tap_item_update` does not fire on the plugin's own `save-item` —
//! `DESIGN.md` Drift 3); this is the guarantee that survives if that changes.

use serde_json::{Value, json};

use crate::columns::USER_OWNED;
use crate::error::{CoreError, CoreResult};
use crate::model::DeviceOverlay;

/// Item field names carrying the device overlay.
///
/// The `field_` prefix is the convention the post-M3 plugins follow; the
/// pre-existing netgrasp skeleton used bare names, and this build moves to the
/// prefixed form because the skeleton's types had never been registered against
/// real data.
pub const FIELD_OWNER: &str = "field_owner";
/// Free-text notes an admin keeps about the device.
pub const FIELD_NOTES: &str = "field_notes";
/// Whether the device is hidden from the default lists.
pub const FIELD_HIDDEN: &str = "field_hidden";
/// Whether the device's arrivals and departures are notable.
pub const FIELD_NOTIFY: &str = "field_notify";

/// Person Item fields.
pub const FIELD_PERSON_NOTES: &str = "field_notes";
/// Whether to announce this person arriving.
pub const FIELD_NOTIFY_ARRIVE: &str = "field_notify_arrive";
/// Whether to announce this person leaving.
pub const FIELD_NOTIFY_DEPART: &str = "field_notify_depart";

/// A statement ready for the `db` host: SQL with `$n` placeholders, its bound
/// parameters, and the user-owned columns it writes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Statement {
    /// SQL with positional placeholders. Never interpolates a value.
    pub sql: String,
    /// Parameters, in placeholder order.
    pub params: Vec<Value>,
    /// The columns this statement assigns, for assertion and for logging.
    pub columns: Vec<String>,
}

/// Read a field that may be stored flat or wrapped as `{"value": …}`.
///
/// Both shapes are live in one install: a plugin's `save-item` writes whatever
/// it was handed, and the admin content form writes flat
/// (`G-ITEM-FORM-MISMATCH`). Accepting either is cheaper and less brittle than
/// depending on which writer touched the Item last.
#[must_use]
pub fn field<'a>(item: &'a Value, name: &str) -> Option<&'a Value> {
    let raw = item.get("fields")?.get(name)?;
    Some(raw.get("value").unwrap_or(raw))
}

/// Read a field as a trimmed string. Absent, null and blank all read as `None`.
#[must_use]
pub fn field_str(item: &Value, name: &str) -> Option<String> {
    match field(item, name)? {
        Value::String(s) if !s.trim().is_empty() => Some(s.trim().to_string()),
        Value::String(_) | Value::Null => None,
        other => Some(other.to_string()),
    }
}

/// Read a field as a boolean, tolerating the string and integer spellings an
/// HTML checkbox round-trip produces (`"1"`, `"true"`, `"on"`, `1`).
#[must_use]
pub fn field_bool(item: &Value, name: &str) -> bool {
    match field(item, name) {
        Some(Value::Bool(b)) => *b,
        Some(Value::Number(n)) => n.as_i64().unwrap_or(0) != 0,
        Some(Value::String(s)) => {
            matches!(
                s.trim().to_ascii_lowercase().as_str(),
                "1" | "true" | "on" | "yes"
            )
        }
        _ => false,
    }
}

/// Extract the user-owned overlay from a saved `ng_device` Item.
///
/// The title becomes `display_name`: the title is what an admin edits on the
/// content form, so giving the label a second editable home as a field would
/// mean two writers for one value.
///
/// # Errors
///
/// [`CoreError::Invalid`] when the payload carries no usable title, which would
/// otherwise blank a device's name on the daemon side.
pub fn overlay_from_item(item: &Value) -> CoreResult<DeviceOverlay> {
    let display_name = item
        .get("title")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|t| !t.is_empty())
        .ok_or_else(|| CoreError::Invalid("device item has no title".into()))?
        .to_string();

    Ok(DeviceOverlay {
        display_name,
        owner_item_id: field_str(item, FIELD_OWNER),
        notes: field_str(item, FIELD_NOTES),
        hidden: field_bool(item, FIELD_HIDDEN),
        notify: field_bool(item, FIELD_NOTIFY),
    })
}

/// Build the one statement an admin's device edit produces.
///
/// The `SET` list is generated from [`USER_OWNED`], so it is impossible for this
/// function to emit a column outside that set — including `sync_state`, whose
/// absence is what stops the edit from re-triggering a sync pass.
///
/// The row is addressed by `trovato_item_id`, not by the device's primary key,
/// because the Item is the only identifier the tap payload carries. A device row
/// that has not been linked yet simply matches nothing, which is correct: an
/// unlinked row has no Item for anyone to have edited.
///
/// # `daemon_fallback` and why `display_name` is sometimes cleared
///
/// `daemon_fallback` is what [`crate::sync::daemon_title`] would call this
/// device from the daemon's observations alone. If the admin's title still
/// equals it, the admin did not rename anything — they edited the notes, or the
/// owner, and the title came along unchanged. Storing it as `display_name` would
/// **pin the device's name**: `display_name` outranks `hostname` in
/// [`crate::sync::derive_title`], so the device would keep its MAC as a label
/// forever even after the daemon resolved a hostname, as a side effect of
/// editing an unrelated field.
///
/// So an unchanged title clears `display_name` instead. The device goes back to
/// tracking what the daemon knows, and an admin who actually types a name gets it
/// stored. Pass `None` when the daemon's view is unavailable, which stores the
/// title unconditionally — the safe direction, since it loses tracking rather
/// than losing a name a human typed.
///
/// # Errors
///
/// [`CoreError::Invalid`] when `item_id` is blank.
pub fn build_update(
    item_id: &str,
    overlay: &DeviceOverlay,
    daemon_fallback: Option<&str>,
) -> CoreResult<Statement> {
    let item_id = item_id.trim();
    if item_id.is_empty() {
        return Err(CoreError::Invalid("write-back needs an item id".into()));
    }

    let display_name = match daemon_fallback {
        Some(f) if f == overlay.display_name => Value::Null,
        _ => json!(overlay.display_name),
    };

    let mut assignments = Vec::with_capacity(USER_OWNED.len());
    let mut params: Vec<Value> = Vec::with_capacity(USER_OWNED.len() + 1);
    let mut columns = Vec::with_capacity(USER_OWNED.len());

    for column in USER_OWNED {
        // Cast at the placeholder rather than trusting the driver to infer a
        // type for a JSON null: `owner_item_id` is a uuid column and an
        // untyped NULL against it is the `invalid input syntax for type uuid`
        // failure mode that G-EXPOSED-FILTER-NO-MATCH-ALL turns up elsewhere.
        let (value, cast) = match *column {
            "display_name" => (display_name.clone(), "text"),
            "owner_item_id" => (
                overlay
                    .owner_item_id
                    .as_ref()
                    .map_or(Value::Null, |v| json!(v)),
                "uuid",
            ),
            "notes" => (
                overlay.notes.as_ref().map_or(Value::Null, |v| json!(v)),
                "text",
            ),
            "hidden" => (json!(overlay.hidden), "boolean"),
            "notify" => (json!(overlay.notify), "boolean"),
            // Unreachable while USER_OWNED and DeviceOverlay agree; the compiler
            // cannot prove that, so the mismatch is reported rather than
            // silently writing a wrong column.
            other => {
                return Err(CoreError::Invalid(format!(
                    "user-owned column '{other}' has no overlay value"
                )));
            }
        };
        params.push(value);
        assignments.push(format!("{column} = ${}::{cast}", params.len()));
        columns.push((*column).to_string());
    }

    params.push(json!(item_id));
    let sql = format!(
        "UPDATE ng_devices SET {} WHERE trovato_item_id = ${}::uuid",
        assignments.join(", "),
        params.len()
    );

    Ok(Statement {
        sql,
        params,
        columns,
    })
}

/// Build the statement mirroring an `ng_person` Item into `ng_people`.
///
/// The mirror is one-directional derived state: the daemon reads it to answer
/// "whose device is this" without ever touching the kernel's `item` table
/// (`DESIGN.md` Decision 3). Keyed on the Item id so a re-fired tap is an upsert
/// rather than a duplicate.
///
/// # Errors
///
/// [`CoreError::Invalid`] when the payload has no id or no title.
pub fn build_person_upsert(item: &Value) -> CoreResult<Statement> {
    let id = item
        .get("id")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| CoreError::Invalid("person item has no id".into()))?;
    let name = item
        .get("title")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| CoreError::Invalid("person item has no title".into()))?;

    let columns = vec![
        "item_id".to_string(),
        "name".to_string(),
        "notes".to_string(),
        "notify_arrive".to_string(),
        "notify_depart".to_string(),
    ];

    Ok(Statement {
        sql: "INSERT INTO ng_people (item_id, name, notes, notify_arrive, notify_depart) \
              VALUES ($1::uuid, $2::text, $3::text, $4::boolean, $5::boolean) \
              ON CONFLICT (item_id) DO UPDATE SET \
                  name = EXCLUDED.name, \
                  notes = EXCLUDED.notes, \
                  notify_arrive = EXCLUDED.notify_arrive, \
                  notify_depart = EXCLUDED.notify_depart"
            .to_string(),
        params: vec![
            json!(id),
            json!(name),
            field_str(item, FIELD_PERSON_NOTES).map_or(Value::Null, |v| json!(v)),
            json!(field_bool(item, FIELD_NOTIFY_ARRIVE)),
            json!(field_bool(item, FIELD_NOTIFY_DEPART)),
        ],
        columns,
    })
}

#[cfg(test)]
// Tests are allowed to use unwrap/expect freely.
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;
    use crate::columns::{DAEMON_OWNED, LINK_OWNED};

    const ITEM: &str = "22222222-2222-4222-8222-222222222222";
    const OWNER: &str = "33333333-3333-4333-8333-333333333333";

    fn device_item() -> Value {
        json!({
            "id": ITEM,
            "type": "ng_device",
            "title": "Jeremy's iPhone",
            "fields": {
                FIELD_OWNER: OWNER,
                FIELD_NOTES: "work phone",
                FIELD_HIDDEN: false,
                FIELD_NOTIFY: true,
            }
        })
    }

    // --- field reading ----------------------------------------------------

    #[test]
    fn fields_read_the_same_whether_stored_flat_or_wrapped() {
        let flat = json!({"fields": {"field_notes": "hello"}});
        let wrapped = json!({"fields": {"field_notes": {"value": "hello"}}});
        assert_eq!(field_str(&flat, FIELD_NOTES).unwrap(), "hello");
        assert_eq!(field_str(&wrapped, FIELD_NOTES).unwrap(), "hello");
    }

    #[test]
    fn a_blank_or_absent_field_reads_as_none_not_as_an_empty_string() {
        let item = json!({"fields": {"field_notes": "   ", "field_owner": null}});
        assert!(field_str(&item, FIELD_NOTES).is_none());
        assert!(field_str(&item, FIELD_OWNER).is_none());
        assert!(field_str(&item, "field_missing").is_none());
    }

    /// The admin content form round-trips a checkbox as a string, and a plugin's
    /// own `save-item` writes a real bool. Both have to mean the same thing.
    #[test]
    fn booleans_tolerate_every_spelling_a_checkbox_round_trip_produces() {
        for truthy in [
            json!(true),
            json!(1),
            json!("1"),
            json!("true"),
            json!("on"),
            json!("Yes"),
        ] {
            let item = json!({"fields": {"field_hidden": truthy}});
            assert!(field_bool(&item, FIELD_HIDDEN), "{truthy} should read true");
        }
        for falsy in [
            json!(false),
            json!(0),
            json!("0"),
            json!("off"),
            json!(""),
            Value::Null,
        ] {
            let item = json!({"fields": {"field_hidden": falsy}});
            assert!(
                !field_bool(&item, FIELD_HIDDEN),
                "{falsy} should read false"
            );
        }
        assert!(!field_bool(&json!({}), FIELD_HIDDEN));
    }

    // --- overlay ----------------------------------------------------------

    #[test]
    fn the_overlay_takes_its_display_name_from_the_items_title() {
        let overlay = overlay_from_item(&device_item()).unwrap();
        assert_eq!(overlay.display_name, "Jeremy's iPhone");
        assert_eq!(overlay.owner_item_id.as_deref(), Some(OWNER));
        assert_eq!(overlay.notes.as_deref(), Some("work phone"));
        assert!(!overlay.hidden);
        assert!(overlay.notify);
    }

    #[test]
    fn an_item_with_no_usable_title_is_refused_rather_than_blanking_the_name() {
        for bad in [json!({"id": ITEM}), json!({"id": ITEM, "title": "   "})] {
            let err = overlay_from_item(&bad).unwrap_err();
            assert!(matches!(err, CoreError::Invalid(_)), "got {err:?}");
        }
    }

    // --- column discipline ------------------------------------------------

    /// The scope's "daemon columns never clobbered by the plugin", asserted on
    /// the statement's own column list rather than by grepping its SQL.
    #[test]
    fn the_write_back_assigns_every_user_column_and_no_other() {
        let stmt = build_update(ITEM, &overlay_from_item(&device_item()).unwrap(), None).unwrap();
        let mut written = stmt.columns.clone();
        written.sort();
        let mut expected: Vec<String> = USER_OWNED.iter().map(|c| (*c).to_string()).collect();
        expected.sort();
        assert_eq!(written, expected);

        for daemon in DAEMON_OWNED {
            assert!(
                !stmt.columns.contains(&(*daemon).to_string()),
                "write-back assigns daemon column '{daemon}'"
            );
        }
        for link in LINK_OWNED {
            assert!(
                !stmt.columns.contains(&(*link).to_string()),
                "write-back assigns link column '{link}'"
            );
        }
    }

    /// Belt and braces on the generated SQL itself: a daemon column must not
    /// appear on the left of an assignment. `trovato_item_id` is expected in the
    /// `WHERE`, so the check is scoped to the `SET` clause.
    #[test]
    fn no_daemon_column_appears_in_the_set_clause() {
        let stmt = build_update(ITEM, &overlay_from_item(&device_item()).unwrap(), None).unwrap();
        let set_clause = stmt
            .sql
            .split(" WHERE ")
            .next()
            .expect("statement has a SET clause");
        for daemon in DAEMON_OWNED {
            assert!(
                !set_clause.contains(&format!("{daemon} =")),
                "SET clause assigns daemon column '{daemon}': {set_clause}"
            );
        }
    }

    /// The loop-termination guarantee, stated as a property of the statement:
    /// an admin edit cannot mark the row dirty, so it cannot cause a sync pass.
    #[test]
    fn the_write_back_cannot_raise_sync_state() {
        let stmt = build_update(ITEM, &overlay_from_item(&device_item()).unwrap(), None).unwrap();
        assert!(
            !stmt.sql.contains("sync_state"),
            "write-back mentions sync_state: {}",
            stmt.sql
        );
        assert!(!stmt.columns.iter().any(|c| c == "sync_state"));
    }

    #[test]
    fn the_write_back_binds_every_value_and_interpolates_none() {
        let stmt = build_update(ITEM, &overlay_from_item(&device_item()).unwrap(), None).unwrap();
        // One placeholder per user column plus the WHERE.
        assert_eq!(stmt.params.len(), USER_OWNED.len() + 1);
        for n in 1..=stmt.params.len() {
            assert!(
                stmt.sql.contains(&format!("${n}")),
                "missing placeholder ${n}"
            );
        }
        // No value reached the SQL text.
        assert!(!stmt.sql.contains("Jeremy"));
        assert!(!stmt.sql.contains(OWNER));
        assert!(!stmt.sql.contains(ITEM));
    }

    /// An unowned device binds a typed NULL, not an empty string: `owner_item_id`
    /// is a uuid column and `''::uuid` raises.
    #[test]
    fn an_unowned_device_binds_a_typed_null_for_its_owner() {
        let item = json!({"id": ITEM, "title": "printer", "fields": {}});
        let stmt = build_update(ITEM, &overlay_from_item(&item).unwrap(), None).unwrap();
        let owner_at = USER_OWNED
            .iter()
            .position(|c| *c == "owner_item_id")
            .unwrap();
        assert_eq!(stmt.params[owner_at], Value::Null);
        assert!(stmt.sql.contains("owner_item_id = $"));
        assert!(stmt.sql.contains("::uuid"));
    }

    // --- name pinning -----------------------------------------------------

    /// An admin who edits the notes without touching the name must not silently
    /// pin the device's label: the title still equals what the daemon would call
    /// it, so `display_name` is cleared and the device keeps tracking whatever
    /// hostname the daemon resolves next.
    #[test]
    fn an_unchanged_title_clears_display_name_rather_than_pinning_the_name() {
        let item = json!({"id": ITEM, "title": "aa:bb:cc:dd:ee:ff", "fields": {}});
        let overlay = overlay_from_item(&item).unwrap();
        let stmt = build_update(ITEM, &overlay, Some("aa:bb:cc:dd:ee:ff")).unwrap();
        let at = USER_OWNED
            .iter()
            .position(|c| *c == "display_name")
            .unwrap();
        assert_eq!(stmt.params[at], Value::Null);
    }

    /// A title the admin actually typed is stored, and outranks everything the
    /// daemon observes from then on.
    #[test]
    fn a_title_the_admin_changed_is_stored_as_the_display_name() {
        let stmt = build_update(
            ITEM,
            &overlay_from_item(&device_item()).unwrap(),
            Some("aa:bb:cc:dd:ee:ff"),
        )
        .unwrap();
        let at = USER_OWNED
            .iter()
            .position(|c| *c == "display_name")
            .unwrap();
        assert_eq!(stmt.params[at], json!("Jeremy's iPhone"));
    }

    /// With no daemon row to compare against, the title is stored — losing
    /// hostname tracking rather than losing a name a human typed.
    #[test]
    fn with_no_daemon_view_the_title_is_stored_unconditionally() {
        let item = json!({"id": ITEM, "title": "aa:bb:cc:dd:ee:ff", "fields": {}});
        let stmt = build_update(ITEM, &overlay_from_item(&item).unwrap(), None).unwrap();
        let at = USER_OWNED
            .iter()
            .position(|c| *c == "display_name")
            .unwrap();
        assert_eq!(stmt.params[at], json!("aa:bb:cc:dd:ee:ff"));
    }

    /// Clearing `display_name` must not turn into clearing the whole column set
    /// — the other four user-owned values still go through.
    #[test]
    fn clearing_display_name_still_writes_every_other_user_column() {
        let item = json!({
            "id": ITEM,
            "title": "nas",
            "fields": {FIELD_NOTES: "kept", FIELD_NOTIFY: true}
        });
        let stmt = build_update(ITEM, &overlay_from_item(&item).unwrap(), Some("nas")).unwrap();
        assert_eq!(stmt.columns.len(), USER_OWNED.len());
        let notes_at = USER_OWNED.iter().position(|c| *c == "notes").unwrap();
        assert_eq!(stmt.params[notes_at], json!("kept"));
    }

    #[test]
    fn a_write_back_with_no_item_id_is_refused() {
        let err = build_update("  ", &DeviceOverlay::default(), None).unwrap_err();
        assert!(matches!(err, CoreError::Invalid(_)), "got {err:?}");
    }

    #[test]
    fn the_write_back_addresses_the_row_by_its_item_link() {
        let stmt = build_update(ITEM, &overlay_from_item(&device_item()).unwrap(), None).unwrap();
        assert!(stmt.sql.contains("WHERE trovato_item_id = $"));
        assert_eq!(stmt.params.last().unwrap(), &json!(ITEM));
    }

    // --- person mirror ----------------------------------------------------

    #[test]
    fn a_person_mirror_is_an_upsert_keyed_on_the_item_id() {
        let item = json!({
            "id": OWNER,
            "title": "Jeremy",
            "fields": {"field_notes": "household", "field_notify_arrive": true}
        });
        let stmt = build_person_upsert(&item).unwrap();
        assert!(stmt.sql.contains("ON CONFLICT (item_id) DO UPDATE"));
        assert_eq!(stmt.params[0], json!(OWNER));
        assert_eq!(stmt.params[1], json!("Jeremy"));
        assert_eq!(stmt.params[3], json!(true));
        assert_eq!(stmt.params[4], json!(false));
    }

    /// At-least-once and a human clicking save twice are the same event as far
    /// as this row is concerned.
    #[test]
    fn a_repeated_person_mirror_produces_an_identical_statement() {
        let item = json!({"id": OWNER, "title": "Jeremy", "fields": {}});
        assert_eq!(
            build_person_upsert(&item).unwrap(),
            build_person_upsert(&item).unwrap()
        );
    }

    #[test]
    fn a_person_with_no_id_or_no_title_is_refused() {
        for bad in [
            json!({"title": "Jeremy"}),
            json!({"id": OWNER}),
            json!({"id": "", "title": "Jeremy"}),
        ] {
            assert!(build_person_upsert(&bad).is_err(), "accepted {bad}");
        }
    }
}
